# Generated by Django 5.2.8 on 2025-11-24 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=300, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='AuxiliaryCardIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название картотеки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название комплекта')),
                ('auxiliary_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_app.auxiliarycardindex')),
            ],
            options={
                'verbose_name': 'Комплект',
                'verbose_name_plural': 'Комплекты',
            },
        ),
        migrations.CreateModel(
            name='MovementAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=100, unique=True, verbose_name='Номер акта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания акта')),
                ('movement_type', models.CharField(choices=[('receive', 'Прием на хранение'), ('transfer_exhibition', 'Передача на выставку'), ('return', 'Возвращение с выставки'), ('write_off', 'Списание'), ('internal_transfer', 'Внутренний перевод')], max_length=30, verbose_name='Тип акта')),
                ('museum_director_name', models.CharField(blank=True, max_length=200, verbose_name='Руководитель музея')),
                ('fund_keeper_name', models.CharField(blank=True, max_length=200, verbose_name='Хранитель фонда')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название организации')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_app.address')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название выставки')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('location_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitions', to='museum_app.address')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitions', to='museum_app.organization')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
            },
        ),
        migrations.CreateModel(
            name='StorageFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название фонда')),
                ('fund_type', models.CharField(choices=[('painting', 'Живопись'), ('graphics', 'Графика'), ('icon', 'Икона'), ('sculpture', 'Скульптура'), ('dpa', 'ДПИ'), ('numismatics', 'Нумизматика'), ('archaeology', 'Археология'), ('manuscripts', 'Рукописи'), ('rare_book', 'Редкая книга'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Тип фонда')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_app.address', verbose_name='Адрес фонда')),
            ],
            options={
                'verbose_name': 'Фонд',
                'verbose_name_plural': 'Фонды',
            },
        ),
        migrations.CreateModel(
            name='MuseumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инв. номер')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('creation_exact', models.BooleanField(default=True, help_text='True — точная, False — приблизительная', verbose_name='Точная дата')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_written_off', models.BooleanField(default=False, verbose_name='Списан')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_app.author')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='museum_app.collection')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='museum_app.storagefund')),
            ],
            options={
                'verbose_name': 'Музейный предмет',
                'verbose_name_plural': 'Музейные предметы',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receive', 'Прием на хранение'), ('transfer_exhibition', 'Передача на выставку'), ('return', 'Возвращение с выставки'), ('write_off', 'Списание'), ('internal_transfer', 'Внутренний перевод')], max_length=30, verbose_name='Тип движения')),
                ('date', models.DateField(verbose_name='Дата движения')),
                ('note', models.TextField(blank=True, verbose_name='Заметки')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='museum_app.collection')),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_app.exhibition')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='museum_app.movementact')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='museum_app.museumitem')),
                ('external_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum_app.organization')),
                ('from_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='museum_app.storagefund')),
                ('to_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='museum_app.storagefund')),
            ],
        ),
        migrations.AddField(
            model_name='auxiliarycardindex',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aux_indices', to='museum_app.storagefund'),
        ),
        migrations.CreateModel(
            name='ExhibitionParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_as_part_of_collection', models.BooleanField(default=False, verbose_name='Как часть комплекта')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='museum_app.exhibition')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to='museum_app.museumitem')),
            ],
            options={
                'unique_together': {('item', 'exhibition')},
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_note', models.CharField(blank=True, max_length=200, verbose_name='Позиция в комплекте')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='museum_app.collection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_link', to='museum_app.museumitem')),
            ],
            options={
                'unique_together': {('collection', 'item')},
            },
        ),
    ]
